fields_for_frontend:
  - article_id
  - article_name
  - writer_name
  - review_type
  - genre
  - distribution_platform
  - short_summary
  - summary
  - writer_name
  - image_vertical
  - author_image_square
  - url
  - name

fields_for_llm:
  - article_name
  - writer_name
  - publish_time
  - text


bucket_name : ask_haaretz
embedding:
  embedding_model_name : text-multilingual-embedding-002
  embedding_dimensionality : 768
qdrant:
  MIN_SCORE_THRESHOLD: 0.8
  SEARCH_LIMIT: 2
  qdrant_url: "from env"
  qdrant_collection_name: movie-recommendation-chatbot
  embedding_metric: cosine

llm:
  GOOGLE_API_KEY: "from env"
  llm_model_name: gemini-2.5-flash-preview-04-17
