

return_fields:
  article_name: שם המאמר
  article_id:  מזהה מאמר
  writer_name:  שם הכותב/ת
  publish_time: זמן פרסום
  section_primary: מדור
  text: כתבה



bucket_name : ask-haaretz
embedding:
  embedding_model_name : text-multilingual-embedding-002
  embedding_dimensionality : 768
qdrant:
  MIN_SCORE_THRESHOLD: 0.7
  SEARCH_LIMIT: 2
  qdrant_url: "from env"
  qdrant_collection_name: ask_haaretz
  embedding_metric: cosine

llm:
  GOOGLE_API_KEY: "from env"
  llm_model_name: gemini-2.0-flash
