fields_for_frontend:
  - article_id
  - article_name
  - writer_name
  - review_type
  - genre
  - distribution_platform
  - short_summary
  - summary
  - writer_name
  - image_vertical
  - author_image_square
  - url
  - name

fields_for_llm:
  - article_name
  - writer_name
  - publish_time
  - text
  - article_id
